---
abstract: 'Search Complex Data Structures'
author:
  - 'Al Newkirk <anewkirk@ana.io>'
build_requires:
  perl: v5.10.0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Seek
requires:
  Hash::Flatten: 1.19
  Mo: 0.38
  perl: v5.10.0
resources:
  bugtracker: https://github.com/alnewkirk/Data-Seek/issues
  homepage: https://metacpan.org/pod/Data::Seek
  repository: git://github.com/alnewkirk/Data-Seek.git
version: 0.05
x_authority: cpan:AWNCORP
